### ISSUE TITLE
  prisma:GeneratorProcess Error: ENOENT: no such file or directory, scandir '...\node_modules\prisma-erd-generator\node_modules\@prisma\engines' +1ms

### ISSUE THREAD

**Issue by janpio** [keonik/prisma-erd-generator#1]
I think the logic to find the binary does not work properly when using the generator via Npm:

```
C:\Users\Jan\Documents\throwaway\repro8264>npx prisma generate
  prisma:loadEnv project root found at C:\Users\Jan\Documents\throwaway\repro8264\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\repro8264\.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3:
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server (Preview) and MongoDB (Preview).
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6:
Environment variables loaded from .env
  prisma:engines using Node API: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +2ms
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\repro8264\node_modules\prisma\query-engine-windows.exe +0ms
  prisma:getDMMF Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\repro8264\node_modules\prisma\query-engine-windows.exe +0ms
  prisma:generator prismaCLIDir C:\Users\Jan\Documents\throwaway\repro8264\node_modules\prisma +0ms
  prisma:generator prismaClientDir C:\Users\Jan\Documents\throwaway\repro8264\node_modules\@prisma\client +0ms
  prisma:generator baseDir C:\Users\Jan\Documents\throwaway\repro8264\prisma +1ms
  prisma:GeneratorProcess internal/fs/utils.js:307 +0ms
  prisma:GeneratorProcess     throw err; +0ms
  prisma:GeneratorProcess     ^ +1ms
  prisma:GeneratorProcess Error: ENOENT: no such file or directory, scandir 'C:\Users\Jan\Documents\throwaway\repro8264\node_modules\prisma-erd-generator\node_modules\@prisma\engines' +1ms
  prisma:GeneratorProcess     at Object.readdirSync (fs.js:1021:3) +1ms
  prisma:GeneratorProcess     at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\repro8264\node_modules\prisma-erd-generator\dist\generate.js:30:33) +0ms
  prisma:GeneratorProcess     at Module._compile (internal/modules/cjs/loader.js:1063:30) +1ms
  prisma:GeneratorProcess     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) +1ms
  prisma:GeneratorProcess     at Module.load (internal/modules/cjs/loader.js:928:32) +1ms
  prisma:GeneratorProcess     at Function.Module._load (internal/modules/cjs/loader.js:769:14) +1ms
  prisma:GeneratorProcess     at Module.require (internal/modules/cjs/loader.js:952:19) +0ms
  prisma:GeneratorProcess     at require (internal/modules/cjs/helpers.js:88:18) +1ms
  prisma:GeneratorProcess     at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\repro8264\node_modules\prisma-erd-generator\dist\index.js:8:36) +1ms
  prisma:GeneratorProcess     at Module._compile (internal/modules/cjs/loader.js:1063:30) { +1ms
  prisma:GeneratorProcess   errno: -4058, +1ms
  prisma:GeneratorProcess   syscall: 'scandir', +0ms
  prisma:GeneratorProcess   code: 'ENOENT', +1ms
  prisma:GeneratorProcess   path: 'C:\\Users\\Jan\\Documents\\throwaway\\repro8264\\node_modules\\prisma-erd-generator\\node_modules\\@prisma\\engines' +1ms
  prisma:GeneratorProcess } +0ms
  prisma:GeneratorProcess 2021-07-16T12:40:18.130Z prisma:client:generator requiredEngine: queryEngine +736ms
```

Adding `'..', '..', ` to the path it tries to read, makes it access the correct dependency folder and let's it progress further.

In theory you should not even have to read the dependency like that at all, but request the correct generator in the manifest. Unfortunately we do not have good documentation on it, but it would look like this: https://github.com/maoosi/prisma-appsync/blob/feae1a466490c610a1f2d58a9cfb85971114ac13/src/generator/prisma-appsync.ts#L16

**Comment by keonik** [comment]
@janpio I've tried adding the required engines section

```ts
    requiresEngines: ['queryEngine']
```

I pushed that change out to the next version to test and I'm getting the same error I got before installing the engine

```bash
 prisma generate

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Generator at prisma-erd-generator could not start:

node:internal/fs/utils:320
    throw err;
    ^
Error: ENOENT: no such file or directory, scandir '/Users/jfay/git/bag-tag/node_modules/prisma-erd-generator/node_modules/@prisma/engines'
    at Object.readdirSync (node:fs:1039:3)
    at Object.<anonymous> (/Users/jfay/git/bag-tag/node_modules/prisma-erd-generator/dist/generate.js:30:33)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/jfay/git/bag-tag/node_modules/prisma-erd-generator/dist/index.js:8:36)
    at Module._compile (node:internal/modules/cjs/loader:1108:14) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/jfay/git/bag-tag/node_modules/prisma-erd-generator/node_modules/@prisma/engines'
```

I might need some documentation on this to figure it out. What you recommended didn't seem to let me delete the engine

**Comment by janpio** [comment]
Nice that you could figure out how this is actually supposed to be used - this implementation is now our internal reference and good example :D
