### ISSUE TITLE
Command failed when i try generator

### ISSUE THREAD

**Issue by lokize** [keonik/prisma-erd-generator#123]
Hi, i have this error when i try run npx prisma generate, I can run with the md extension but when I try to use png or svg this error occurs

![image](https://user-images.githubusercontent.com/19701630/185103468-71866e50-68cc-47ff-b4cd-b6a6716a4795.png)

**Comment by keonik** [comment]
Hey @lokize this might be a duplicate issue so could you share your OS, node version, and do some validation to see if that path to mmdc engine exists?

```bash
/root/developer/Exp/Area-do-Cliente-Ceres-Sistemas/node_modules/.bin/mmdc
```

**Comment by lokize** [comment]
thanks for help, yes the path exists, when i try gerenate with extension ".md" this worked

**Comment by keonik** [comment]
That’s the confusing part. When you run with the output file as .md it skips calling that script because we’ve already translated the prisma dml to mermaid and it gets written straight to file. Any other formats get run through this script. Do another check to make sure that exists in the directory

**Comment by lokize** [comment]
i check again and the folder and path exists...

**Comment by keonik** [comment]
Okay cool. Go ahead and [enable debug mode ](https://github.com/keonik/prisma-erd-generator#debugging) and take a look at your generated mermaid file in step 3 outputted to `prisma/debug/3-...`. If it works in markdown it should work through the mermaid CLI so try to call the CLI manually and ensure it generates your svg/png etc. They don't really show much for debugging if it fails in the CLI. Depending on if you get through manually calling the CLI we would keep troubleshooting or open an issue with mermaid cli.

**Comment by keonik** [comment]
Share your OS and node version as well. Most of these fails are happening for windows users

**Comment by lokize** [comment]
i using wsl2 with CentOS9 Stream, nvm with nodejs v16.16.0

**Comment by d0lb33** [comment]
Same error here, I ran the command manually and it seems to be a puppeteer issue.
![image](https://user-images.githubusercontent.com/18106388/195123317-36f008b0-3a32-4853-9956-65fcbab9b1d9.png)

**Comment by d0lb33** [comment]
I ran:
`sudo apt-get install -y libgbm-dev`

And now I get this error:
![image](https://user-images.githubusercontent.com/18106388/195124557-d913db00-edc4-4548-bbef-d9f0ac3b3d9f.png)

Node Version: v16.17.1
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by d0lb33** [comment]
So what worked for me was following the mermaid readme:
![image](https://user-images.githubusercontent.com/18106388/195127770-a18a85e8-f257-44dc-a39b-ec74221d4374.png)


I made this file and added it to my manual command.

**Comment by Sephyros** [comment]
I had the same problem as the author of the issue, I use Windows 11 with WSL2 (Ubuntu 22.04.1 - 5.15.68.1-microsoft-standard-WSL2) and I didn't have any special characters or spaces in the path, everything was resolved when I installed the lib " libasound2", don't ask me what this library has to do with an svg generator, but as I said, that's what solved it.

**Comment by pmdpaula** [comment]
I've tried averything above and what worked for me was:
`sudo apt-get install libxkbcommon-x11-0`

I'm using Win10 WSL2 Ubuntu22.02
Node v18.12.0

**Comment by meli-tortelli** [comment]
i've tried your solution @pmdpaula and @Sephyros  but both didn't worked for me, i'm still getting the same error. there's another thing that i can try to do to solve this error?
i'm using windows 11 with WSL Ubuntu v22.04.1, nvm with node v18.12.0

![image](https://user-images.githubusercontent.com/56207729/200104188-a81e31fa-f37a-40e4-925d-33e16b481dcd.png)

**Comment by meli-tortelli** [comment]
i solved already. i guess it was a duplicate module issue with the prisma generator-helper. i just had to remove the module, run yarn install and then ran again npx prisma generate.

so if anyone is having this same issue maybe try to do the same.

![image](https://user-images.githubusercontent.com/56207729/200105698-f6bfcd90-171d-4aed-a420-bc9e1720eaa6.png)

**Comment by pmdpaula** [comment]
> i solved already. i guess it was a duplicate module issue with the prisma generator-helper. i just had to remove the module, run yarn install and then ran again npx prisma generate.
> 
> so if anyone is having this same issue maybe try to do the same.
> 
> ![image](https://user-images.githubusercontent.com/56207729/200105698-f6bfcd90-171d-4aed-a420-bc9e1720eaa6.png)
> 

It didn't work for me. I've tried it before.

**Comment by Siegrift** [comment]
I experienced a similar issue but my error cause (and also fix) was different. I ran the failed command myself to see what is the error.

```
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1045629).
    at ChromeLauncher.launch (file:///Users/emanueltesar/vacuumlabs/api3/oev-relay/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:64:23)
    at async run (file:///Users/emanueltesar/vacuumlabs/api3/oev-relay/node_modules/@mermaid-js/mermaid-cli/src/index.js:343:19)
    at async cli (file:///Users/emanueltesar/vacuumlabs/api3/oev-relay/node_modules/@mermaid-js/mermaid-cli/src/index.js:138:3)
```

and the fix that worked for me was: https://stackoverflow.com/a/60843949

**Comment by lokize** [comment]
I still have this problem only work with md extension when i try using png, pdf or svg not worked.

**Comment by segheysens** [comment]
On MacOS, this just seemed to be a permissions issue and the command worked (after previously failing) but just using sudo.

**Comment by maiconloure** [comment]
`sudo apt-get install -y libgbm-dev`
Above command fixed my problem.

**Comment by keonik** [comment]
Did everyone find a resolution on this? As far as I'm seeing it, puppeteer support for node v18 is not there yet. As a workaround we can run the generator and utilize markdown export only.

Options
- Downgrade to node v16
- Export to `.md` file
- Try various install suggestions to get node 18 working or update libraries on your computer
[libgbm-dev](https://github.com/keonik/prisma-erd-generator/issues/123#issuecomment-1399682610), [libxkbcommon](https://github.com/keonik/prisma-erd-generator/issues/123#issuecomment-1304094570), etc.

**Comment by kraighamady** [comment]
I just got this error today.  
Windows 10, Node 19.8.1. 
Was working yesterday and today I got the same issue as above. No changes to my system, just to my schema.

**Comment by sKawashima** [comment]
I got the same error too.
It was Mac OS, Node 18.

After reinstalling Chromium it worked fine.
On M1Mac I had to run `xattr -rc /Applications/Chromium.app`.

When executing the command, it acted like it was trying to start Chromium, so I reinstalled it and executed the above command.
I don't know why this solved the problem.

Is Chromium required to run this library?

**Comment by keonik** [comment]
@lokize were you able to figure a solution? This issue turned into a good troubleshooting guide of ideas for each OS. I might pin it for reference

**Comment by nicel3d** [comment]
For Windows11 and wsl2.
The transition from version `1.8.0` to `1.11.0` caused an error in generating the svg file, creating my own `puppeteerConfig.json` solved the problem:


`schema.prisma`
```
generator erd {
  provider        = "prisma-erd-generator"
  output          = "./ERD.svg"
  puppeteerConfig = "./puppeteerConfig.json"
}
```

 `puppeteerConfig.json` 
```
{ "logLevel": "error" }
```

**Comment by fullstackzach** [comment]
@nicel3d's solution worked for me and was straightforward!

here's my config

generator erd {
  provider        = "prisma-erd-generator"
  puppeteerConfig = "./prisma/puppeteerConfig.json"
}

**Comment by akd-io** [comment]
I'm getting errors in my GitHub workflow too. Works fine locally on my Mac:

```
> prisma generate

Prisma schema loaded from prisma/schema.prisma
Error: 
✔ Generated Prisma Client (v5.2.0) to ./prisma/generated/prisma-client in 186ms

Command failed: "/home/runner/work/redacted/redacted/node_modules/.bin/mmdc" -i "/tmp/prisma-erd-wvWwyT/prisma.mmd" -o "/home/runner/work/redacted/redacted/prisma/generated/ERD.svg" -c "/tmp/prisma-erd-wvWwyT/config.json" -p "/tmp/prisma-erd-wvWwyT/puppeteerConfig.json"


 ELIFECYCLE  Command failed with exit code 1.
```

My `prisma.schema` includes:
```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x", "debian-openssl-1.1.x"]
  output = "./generated/prisma-client"
}

generator erd {
  provider = "prisma-erd-generator"
  output = "./generated/ERD.svg"
}
```

**Comment by cyrus-za** [comment]
I get that same error when trying to build it on vercel. Works locally though

**Comment by keonik** [comment]
> I get that same error when trying to build it on vercel. Works locally though

@cyrus-za Do you need or want it to run on the build within vercel? 

@akd-io for you and @cyrus-za we need to work backwards to see if mmdc exists, then enable debugging logs to see why the command is failing.

If you are okay with just publishing to the git repository I recommend adding ERD_DISABLE to the github job or the vercel build job. On the off chance you're trying to serve the SVG within the project you do probably need it in which I'd recommend going down that mmdc location and log enabling route.

**Comment by cyrus-za** [comment]
yes trying to serve the svg on a standalone vercel project that run within the same monorepo. That way we always got an up to date svg hosted at a url that we can open during architecture meetings

**Comment by keonik** [comment]
Going through the backlog 👋. This one is quite old and the toolchain has moved a lot since (Prisma 7 support, engine-less generation, Node 20+). Could you confirm whether it still reproduces on the latest 2.4.x? If so, a minimal schema + your `prisma -v` and `node -v` output would help a lot. I'll close as stale in a few weeks if it's no longer reproducible, but happy to keep it open if it is.

**Comment by keonik** [comment]
Closing this as stale.

This was filed in 2022 against a version of the generator that no longer exists in any meaningful sense — since then the project moved to engine-less generation on Prisma 5–7, Node 20+, and as of [3.0.0](https://github.com/keonik/prisma-erd-generator/releases/tag/v3.0.0), `@mermaid-js/mermaid-cli` and puppeteer are optional peer dependencies rather than hard ones.

That last change is likely the relevant one here: most of the failures in this thread were the bundled Chromium being unavailable or unusable, and that dependency is no longer installed on your behalf at all. If you render `.md` or `.mmd`, no browser is involved. If you render `.svg` / `.png` / `.pdf`, you install and control the CLI yourself, and a missing one now fails with a message that names the package instead of a generic error.

Happy to reopen — but for anything still broken on 3.0.0, a fresh issue with a minimal schema plus `node -v` and `prisma -v` will be much easier to act on than continuing a three-year-old thread. Thanks to everyone who added detail here over the years.
