### ISSUE TITLE
I can not create ER image...

### ISSUE THREAD

**Issue by y-koyamatsu** [keonik/prisma-erd-generator#60]
y-koyamatsu@koyamatsuyukinoMacBook-Pro prisma % npx prisma generate

```
Environment variables loaded from ../.env
Prisma schema loaded from schema.prisma
Error: 
Error: Command failed: ../../ER図_v2'/node_modules/.bin/mmdc -i /var/folders/sw/5cfrfxkx6lj1z_d1ph0hrvpc0000gn/T/prisma-erd-u7WZMn/prisma.mmd -o /Users/y-koyamatsu/Desktop/KMJ/ER図_v2'/ERD.svg -t forest -c /var/folders/sw/5cfrfxkx6lj1z_d1ph0hrvpc0000gn/T/prisma-erd-u7WZMn/config.json
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exports.default [as onGenerate] (/Users/y-koyamatsu/Desktop/KMJ/ER図_v2'/node_modules/prisma-erd-generator/dist/generate.js:197:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LineStream.<anonymous> (/Users/y-koyamatsu/Desktop/KMJ/ER図_v2'/node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)

```

I got above error.... How I can do to slove this???

```
  "dependencies": {
    "@prisma/client": "^3.7.0",
    "mermaid": "^8.13.10",
    "prisma-erd-generator": "^0.9.0"
  }
```

**Comment by T3NED** [comment]
I am experiencing the same issue on both Windows and Linux.

### Error
```
Environment variables loaded from .env
Prisma schema loaded from src\schema.prisma
Error: 
✔ Generated Prisma Client (3.9.1 | library) to .\src\client in 47ms

Error: Command failed: find ../.. -name mmdc
FIND: Parameter format not correct
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exports.default [as onGenerate] (B:\Projects\[REDACTED]\versions\v2\lib\node_modules\prisma-erd-generator\dist\generate.js:185:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LineStream.<anonymous> (B:\Projects\[REDACTED]\versions\v2\lib\node_modules\@prisma\generator-helper\dist\generatorHandler.js:36:24)
```

### Dependencies
```
"devDependencies": {
    "@types/node": "^17.0.13",
    "prisma": "^3.9.1",
    "prisma-erd-generator": "^0.9.0",
    "typescript": "^4.5.5"
}
```

**Comment by keonik** [comment]
Many issues are happening around mermaid cli usage. Could you try installing `@mermaid-js/mermaid-cli` as a dev dependency and see if that solves the issue? I'm hoping that works for you.

**Comment by T3NED** [comment]
> Many issues are happening around mermaid cli usage. Could you try installing `@mermaid-js/mermaid-cli` as a dev dependency and see if that solves the issue? I'm hoping that works for you.

Amazing! All is working now, thank you 👍

**Comment by keonik** [comment]
I’ll add this to the docs. Apparently the labeling of that library as a peer dependency isn’t installing it for everyone.
