### ISSUE TITLE
Running tests locally fails

### ISSUE THREAD

**Issue by janpio** [keonik/prisma-erd-generator#68]
```
Error: 
Error: could not parse datamodel
    at Object.exports.default [as onGenerate] (/workspace/prisma-erd-generator/dist/generate.js:175:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LineStream.<anonymous> (/workspace/prisma-erd-generator/node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)


 FAIL  __tests__/Enums.ts (6.909 s)
  ● enums.prisma

    Command failed: npx prisma generate --schema ./prisma/enums.prisma
    Error: 
    Error: could not parse datamodel

      173 |         const datamodelString = await parseDatamodel(queryEngine, options.datamodel, tmpDir);
      174 |         if (!datamodelString)
    > 175 |             throw new Error('could not parse datamodel');
          |                   ^
      176 |         let dml = JSON.parse(datamodelString);
      177 |         // updating dml to map to db table and column names (@map && @@map)
      178 |         dml.models = (0, exports.mapPrismaToDb)(dml.models, options.datamodel);

      at Object.exports.default [as onGenerate] (dist/generate.js:175:19)
      at async LineStream.<anonymous> (node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)
      at Object.<anonymous> (__tests__/Enums.ts:7:19)

Error: 
Error: Command failed: /workspace/prisma-erd-generator/node_modules/.bin/mmdc -i /tmp/prisma-erd-r1kvOZ/prisma.mmd -o /workspace/prisma-erd-generator/__tests__/ManyToMany.svg -t forest -c /tmp/prisma-erd-r1kvOZ/config.json
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exports.default [as onGenerate] (/workspace/prisma-erd-generator/dist/generate.js:203:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LineStream.<anonymous> (/workspace/prisma-erd-generator/node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)


 FAIL  __tests__/manyToMany.test.ts (7.413 s)
  ● many-to-many.prisma

    Command failed: npx prisma generate --schema ./prisma/many-to-many.prisma
    Error: 
    Error: Command failed: /workspace/prisma-erd-generator/node_modules/.bin/mmdc -i /tmp/prisma-erd-r1kvOZ/prisma.mmd -o /workspace/prisma-erd-generator/__tests__/ManyToMany.svg -t forest -c /tmp/prisma-erd-r1kvOZ/config.json

      201 |             }
      202 |         }
    > 203 |         child_process.execSync(`${mermaidCliNodePath} -i ${tempMermaidFile} -o ${output} -t ${theme} -c ${tempConfigFile}`, {
          |                       ^
      204 |             stdio: 'ignore',
      205 |         });
      206 |         // throw error if file was not created

      at Object.exports.default [as onGenerate] (dist/generate.js:203:23)
      at async LineStream.<anonymous> (node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)
      at Object.<anonymous> (__tests__/manyToMany.test.ts:7:19)

Error: 
Error: Command failed: /workspace/prisma-erd-generator/node_modules/.bin/mmdc -i /tmp/prisma-erd-rFlswF/prisma.mmd -o /workspace/prisma-erd-generator/ERD.svg -t default -c /tmp/prisma-erd-rFlswF/config.json
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exports.default [as onGenerate] (/workspace/prisma-erd-generator/dist/generate.js:203:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LineStream.<anonymous> (/workspace/prisma-erd-generator/node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)


 FAIL  __tests__/genericModels.test.ts (7.581 s)
  ● schema.prisma

    Command failed: npx prisma generate
    Error: 
    Error: Command failed: /workspace/prisma-erd-generator/node_modules/.bin/mmdc -i /tmp/prisma-erd-rFlswF/prisma.mmd -o /workspace/prisma-erd-generator/ERD.svg -t default -c /tmp/prisma-erd-rFlswF/config.json

      201 |             }
      202 |         }
    > 203 |         child_process.execSync(`${mermaidCliNodePath} -i ${tempMermaidFile} -o ${output} -t ${theme} -c ${tempConfigFile}`, {
          |                       ^
      204 |             stdio: 'ignore',
      205 |         });
      206 |         // throw error if file was not created

      at Object.exports.default [as onGenerate] (dist/generate.js:203:23)
      at async LineStream.<anonymous> (node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)
      at Object.<anonymous> (__tests__/genericModels.test.ts:5:19)

Error: 
✔ Generated Prisma Client (3.6.0 | library) to ./node_modules/@prisma/client in 63ms

Error: Command failed: /workspace/prisma-erd-generator/node_modules/.bin/mmdc -i /tmp/prisma-erd-m3S4d2/prisma.mmd -o /workspace/prisma-erd-generator/__tests__/36.png -t forest -c /tmp/prisma-erd-m3S4d2/config.json
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exports.default [as onGenerate] (/workspace/prisma-erd-generator/dist/generate.js:203:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LineStream.<anonymous> (/workspace/prisma-erd-generator/node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)


 FAIL  __tests__/issues/36.test.ts (8.099 s)
  ● many-to-many.prisma

    Command failed: npx prisma generate --schema ./prisma/36.prisma
    Error: 
    ✔ Generated Prisma Client (3.6.0 | library) to ./node_modules/@prisma/client in 63ms

    Error: Command failed: /workspace/prisma-erd-generator/node_modules/.bin/mmdc -i /tmp/prisma-erd-m3S4d2/prisma.mmd -o /workspace/prisma-erd-generator/__tests__/36.png -t forest -c /tmp/prisma-erd-m3S4d2/config.json

      201 |             }
      202 |         }
    > 203 |         child_process.execSync(`${mermaidCliNodePath} -i ${tempMermaidFile} -o ${output} -t ${theme} -c ${tempConfigFile}`, {
          |                       ^
      204 |             stdio: 'ignore',
      205 |         });
      206 |         // throw error if file was not created

      at Object.exports.default [as onGenerate] (dist/generate.js:203:23)
      at async LineStream.<anonymous> (node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)
      at Object.<anonymous> (__tests__/issues/36.test.ts:7:19)

Error: 
✔ Generated Prisma Client (3.6.0 | library) to ./node_modules/@prisma/client in 132ms

Error: Command failed: /workspace/prisma-erd-generator/node_modules/.bin/mmdc -i /tmp/prisma-erd-fGfuXi/prisma.mmd -o /workspace/prisma-erd-generator/__tests__/Mappings.svg -t forest -c /tmp/prisma-erd-fGfuXi/config.json
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exports.default [as onGenerate] (/workspace/prisma-erd-generator/dist/generate.js:203:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LineStream.<anonymous> (/workspace/prisma-erd-generator/node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)


 FAIL  __tests__/map.test.ts (8.674 s)
  ● map e2e

    Command failed: npx prisma generate --schema ./prisma/mappings.prisma
    Error: 
    ✔ Generated Prisma Client (3.6.0 | library) to ./node_modules/@prisma/client in 132ms

    Error: Command failed: /workspace/prisma-erd-generator/node_modules/.bin/mmdc -i /tmp/prisma-erd-fGfuXi/prisma.mmd -o /workspace/prisma-erd-generator/__tests__/Mappings.svg -t forest -c /tmp/prisma-erd-fGfuXi/config.json

      201 |             }
      202 |         }
    > 203 |         child_process.execSync(`${mermaidCliNodePath} -i ${tempMermaidFile} -o ${output} -t ${theme} -c ${tempConfigFile}`, {
          |                       ^
      204 |             stdio: 'ignore',
      205 |         });
      206 |         // throw error if file was not created

      at Object.exports.default [as onGenerate] (dist/generate.js:203:23)
      at async LineStream.<anonymous> (node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)
      at Object.<anonymous> (__tests__/map.test.ts:88:19)
```

Not sure what I am doing wrong.

**Comment by janpio** [comment]
Ah, running the command that fails gives me some output:

```
gitpod /workspace/prisma-erd-generator (main) $ /workspace/prisma-erd-generator/node_modules/.bin/mmdc -i /tmp/prisma-erd-r1kvOZ/prisma.mmd -o /workspace/prisma-erd-generator/__tests__/ManyToMany.svg -t forest -c /tmp/prisma-erd-r1kvOZ/config.json
/workspace/prisma-erd-generator/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/workspace/prisma-erd-generator/node_modules/puppeteer/.local-chromium/linux-961656/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/workspace/prisma-erd-generator/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at Interface.<anonymous> (/workspace/prisma-erd-generator/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:219:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I think I remember that from before.

**Comment by janpio** [comment]
I am running this in Gitpod, and this list of commands fixed the problem for me: https://github.com/jankeromnes/gitpodPuppeteerTest/commit/30e4d45343160e1f0d9266e0a17d96a5d5d5a80f (via https://community.gitpod.io/t/using-puppeteer-libnss3-no-file-or-directory-issue-on-gitpod/1762/9)
